name: Test and coverage

on: [pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 2
      - run: |  # simulate modification of source code
          code='package calc\n\nfunc Add(x, y int) int {\nprintln("code again added")\nreturn x + y\n}'
          printf "$code" > calc1.go
          mv calc1.go calc.go
      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: '1.17'
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: test
        uses: docker://ghcr.io/buildpacks/actions/registry/request-add-entry:4.0.1@sha256:71df0770db246ee853235f016e97a0afa5adeceb0bd13ca73a87158df3adcb9b
      - name: Upload coverage to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash)    
