# CIFuzz action for OSS-Fuzz set up of Liblouis.
# CIFuzz documentation:
# - https://google.github.io/oss-fuzz/getting-started/continuous-integration
# Liblouis OSS-Fuzz project:
# - https://github.com/google/oss-fuzz/blob/master/projects/liblouis
# This CI action will build the fuzzers using the Dockerfile and build.sh
# script from the Liblouis OSS-Fuzz project folder. It runs on GitHub's
# servers.
name: CIFuzz
on: [pull_request]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit

    - name: Build Fuzzers
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@d9fddd8c9b5e5c79edc94c3c8783afe41eabc560 # master
      with:
        oss-fuzz-project-name: 'liblouis'
        language: c
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@d9fddd8c9b5e5c79edc94c3c8783afe41eabc560 # master
      with:
        oss-fuzz-project-name: 'liblouis'
        fuzz-seconds: 300
        language: c
    - name: Upload Crash
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
